apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archw1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /archw1
            pathType: Prefix
            backend:
              service:
                name: archw1
                port:
                  number: 8000